### ISSUE TITLE
Compatibilty check with Bitbucket Data-center

### ISSUE THREAD

**Issue by shafemoh** [reconquest/atlassian-pull-request-labels#19]
Hi @Reconquest/pull-request-label
**We have some questions regarding the PR-label add-on to install with our Bitbucket application.**
1. Mainly when I look at the [versions history](https://marketplace.atlassian.com/apps/1219710/free-pull-request-labels-by-reconquest/version-history) I see that the plugin is compatible with Bitbucket server only (7.1.1 - Bitbucket Server 5.0.0 - 7.20.0), So we would like to know if the same is compatible to be installed on Bitbucket Data-center
2. Any timelines for data-center compatible releases?
3. I hope adding the add-on to our bitbucket data-center application doesn't have any accesses to our code in bitbucket?
4. How does the system/server that's hosting Bitbucket application perform after adding this add-on? (Considering that if more projects/repositories start using them, is there any chance of system degradation performance, logs multiplying due to labels,....)?

![image](https://user-images.githubusercontent.com/96038516/154257595-c3c3831d-f323-4f37-91bf-dcd2ee42fb64.png)

**Comment by kovetskiy** [comment]
Hi, @shafemoh 

1. It's not marked as compatible with the new versions since we didn't test the add-on on them. Basically, the add-on is compatible with the Data Center edition because there is virtually no difference Server vs DC when it comes to labeling pull requests.
2. Nope, we don't have any timelines. The add-on is free and currently out of our priorities because of that, but if you really want to see the add-on to be compatible, we can discuss it further via e-mail we@reconquest.io
3. Unfortunately, SDK of Atlassian Bitbucket doesn't enable developers to limit access of add-ons to specific features. So, the add-on has full access to the entire internal Bitbucket subsystem, including access to users, filesystem, etc. But we DO NOT USE these features and only label pull requests as it's said in the description, and the source code is available freely which means you can compile it on your own and install it yourself.
4. We haven't tested this add-on on large Bitbucket instances, but since we follow the same practices which we use on other add-ons which are used on large instances, everything should be fine in terms of logs. Degradation is not what you should expect because it doesn't affect the time it takes to load the page since the labels are loading asynchronously. More than that, it's pretty straightforward logic and has pagination.

**Comment by shafemoh** [comment]
I also see that the plugin has not been updated for the last two years. Any comments there? [versions history](https://marketplace.atlassian.com/apps/1219710/free-pull-request-labels-by-reconquest/version-history)
