### ISSUE TITLE
atlassian-pull-request-labels ..Updated?

### ISSUE THREAD

**Issue by shafemoh** [reconquest/atlassian-pull-request-labels#20]
Hi @Reconquest/pull-request-label,
I see that the PR-label add-on has not been updated for at least a couple of years now. [versions history](https://marketplace.atlassian.com/apps/1219710/free-pull-request-labels-by-reconquest/version-history) Any updates there?

Thanks

**Comment by kovetskiy** [comment]
Hi, basically it is the same reason as for DC, the add-on is free and
available for everyone to contribute, we are not working on it right now
because it is not generating us any profits. If you are asking for some
specific features or you experience some problems with the add-on, you can
send a pull request. If you want a full support, then we can talk about it
and find some solutions, just drop us a line on email ***@***.***
